title: Matěj Volf
logo: "/images/me.jpg"
location: Tábor, Czech republic
description: |
  High school student, Python programmer. Almost proficient with Flask, moderately
  skilled with JavaScript, SQLAlchemy and Python in general.

profile_links:
  - url: https://github.com/mvolfik
    text: GitHub
  - url: https://www.linkedin.com/in/matej-volf/
    text: LinkedIn
  - url: https://mailhide.io/e/8adeL
    text: Email

skills:
  - name: Flask
    value: 5
  - name: Python
    value: 4.3
  - name: JavaScript
    value: 4
  - name: SvelteJS
    value: 4
  - name: Heroku
    value: 3.5
  - name: SQLAlchemy
    value: 3.5
  - name: Git
    value: 3
  - name: Linux
    value: 3
  - name: PostgreSQL
    value: 3

gtag: G-MVBYXVW526

remote_theme: pages-themes/minimal@25df166
sass.sass_dir: _sass

include:
  - .well-known
