import { ensureAccessToken } from "./spotifyAuth.js";
import type { ArtistRecord, TrackRecord } from "./types.js";

const API = "https://api.spotify.com/v1";

async function spotifyFetch(
  pathAndQuery: string,
  init: RequestInit = {},
): Promise<Response> {
  const token = await ensureAccessToken();
  const response = await fetch(`${API}${pathAndQuery}`, {
    ...init,
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
      ...init.headers,
    },
  });
  if (response.status === 429) {
    const retryAfter = Number(response.headers.get("Retry-After") ?? "1");
    console.log(`Rate limited, waiting ${retryAfter}s...`);
    await new Promise((r) => setTimeout(r, (retryAfter + 1) * 1000));
    return spotifyFetch(pathAndQuery, init);
  }
  if (!response.ok) {
    throw new Error(
      `Spotify API ${pathAndQuery} failed: ${response.status} ${await response.text()}`,
    );
  }
  return response;
}

export async function fetchLikedTracks(
  onPage: (tracks: TrackRecord[]) => void,
): Promise<void> {
  const limit = 50;
  let offset = 0;
  for (;;) {
    const res = await spotifyFetch(
      `/me/tracks?limit=${limit}&offset=${offset}`,
    );
    const body = (await res.json()) as {
      items: Array<{
        added_at: string;
        track: {
          id: string;
          name: string;
          popularity: number;
          external_urls: { spotify: string };
          album: { name: string; release_date: string };
          artists: Array<{ id: string; name: string }>;
        };
      }>;
    };
    if (body.items.length === 0) break;
    onPage(
      body.items.map((item) => ({
        id: item.track.id,
        name: item.track.name,
        artistIds: item.track.artists.map((a) => a.id),
        artistNames: item.track.artists.map((a) => a.name),
        album: item.track.album.name,
        releaseDate: item.track.album.release_date,
        popularity: item.track.popularity,
        addedAt: item.added_at,
        url: item.track.external_urls.spotify,
      })),
    );
    if (body.items.length < limit) break;
    offset += limit;
  }
}

export async function fetchArtistGenres(
  artistIds: string[],
): Promise<ArtistRecord[]> {
  const results: ArtistRecord[] = [];
  for (let i = 0; i < artistIds.length; i += 50) {
    const chunk = artistIds.slice(i, i + 50);
    const res = await spotifyFetch(`/artists?ids=${chunk.join(",")}`);
    const body = (await res.json()) as {
      artists: Array<{ id: string; name: string; genres: string[] }>;
    };
    for (const artist of body.artists) {
      results.push({ id: artist.id, name: artist.name, genres: artist.genres });
    }
  }
  return results;
}

export async function getCurrentUserId(): Promise<string> {
  const res = await spotifyFetch("/me");
  const body = (await res.json()) as { id: string };
  return body.id;
}

export async function findOrCreatePlaylist(
  userId: string,
  name: string,
): Promise<string> {
  let offset = 0;
  for (;;) {
    const res = await spotifyFetch(`/me/playlists?limit=50&offset=${offset}`);
    const body = (await res.json()) as {
      items: Array<{ id: string; name: string }>;
      next: string | null;
    };
    const found = body.items.find((p) => p.name === name);
    if (found) return found.id;
    if (!body.next) break;
    offset += 50;
  }
  const res = await spotifyFetch(`/users/${userId}/playlists`, {
    method: "POST",
    body: JSON.stringify({
      name,
      public: false,
      description: "Generated by spotify-vibe-sorter",
    }),
  });
  const body = (await res.json()) as { id: string };
  return body.id;
}

export async function getPlaylistTrackIds(
  playlistId: string,
): Promise<Set<string>> {
  const ids = new Set<string>();
  let url: string | null =
    `/playlists/${playlistId}/tracks?fields=items(track(id)),next&limit=100`;
  while (url) {
    const res: Response = await spotifyFetch(url);
    const body = (await res.json()) as {
      items: Array<{ track: { id: string } | null }>;
      next: string | null;
    };
    for (const item of body.items) {
      if (item.track?.id) ids.add(item.track.id);
    }
    url = body.next ? body.next.replace(API, "") : null;
  }
  return ids;
}

export async function addTracksToPlaylist(
  playlistId: string,
  trackIds: string[],
): Promise<void> {
  for (let i = 0; i < trackIds.length; i += 100) {
    const chunk = trackIds.slice(i, i + 100);
    await spotifyFetch(`/playlists/${playlistId}/tracks`, {
      method: "POST",
      body: JSON.stringify({ uris: chunk.map((id) => `spotify:track:${id}`) }),
    });
  }
}
